apiVersion: v1
kind: Secret
metadata:
  name: fulfillment
  namespace: fulfillment
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_access_key | b64enc }}
  SLACK_TOKEN: {{ .Values.slack.token | b64enc }}
