apiVersion: v1
kind: Service
metadata:
  name: aws-fulfillment
  namespace: aws-fulfillment
spec:
  selector:
    app: aws-fulfillment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
