apiVersion: v1
description: A Helm chart for aws-fulfillment
home: https://github.com/giantswarm/aws-fulfillment
name: aws-fulfillment
version: 0.0.1
annotations:
  application.giantswarm.io/team: "planeteers"